//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int userID { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage ="This field is required")]
        public string username { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required")]
        public string password { get; set; }
        public string securityPhase { get; set; }
        public int attemptCount { get; set; }
        public string ipAddress { get; set; }
        public int statusID { get; set; }
        public int employeeID { get; set; }

        public string LoginErrorMessage { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
